
name: Merge branch rel-7.0 with rel-6.0
on:
  push:
    branches:
      - rel-6.0
jobs:
  merge-rel-7-with-rel-6-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rel-7.0
      - name: Reset promotion branch
        run: |
          git fetch origin rel-6.0:rel-6.0
          git reset --hard rel-6.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-6-0/${{github.run_number}}
          title: Merge branch rel-7.0 with rel-6.0
          body: This PR generated automatically to merge rel-7.0 with rel-6.0. Please review the changed files before merging to prevent any errors that may occur.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
